'''Functions for mesh input/output, halfedge mesh processing with open3d, cutting a halfedge mesh along a curve, and Tutte embedding of a curved triangle to a flat equilateral triangle. '''

import open3d as o3d
import numpy as np
import trimesh
import igl
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d.art3d import Poly3DCollection
# Get vertices as numpy array
from scipy.spatial import cKDTree
from collections import deque
import re


import numpy as np

def write_polyline_to_obj(V=None, filename='polyline.obj'):
    """
    Write a polyline (loop) defined by vertices V to an OBJ file.
    
    Parameters
    ----------
    V : np.ndarray
        A (N, 3) array of vertices.
    filename : str, optional
        Output OBJ filename. Defaults to 'polyline.obj'.
    """
    if V is None:
        raise ValueError("You must provide a NumPy array of vertices.")
    if not isinstance(V, np.ndarray):
        raise TypeError("V must be a NumPy array.")
    if V.ndim != 2 or V.shape[1] != 3:
        raise ValueError("V must have shape (N, 3).")

    N = V.shape[0]
    
    with open(filename, 'w') as f:
        f.write("# OBJ file generated by write_polyline_to_obj\n")
        
        # Write vertices
        for v in V:
            f.write(f"v {v[0]} {v[1]} {v[2]}\n")
        
        # Write line elements: connect each vertex to the next, and last to first
        
        for i in range(1, N ):
            f.write("l ")
            f.write(f"{i} {i+1}\n")
        f.write(f"l {N} 1\n")  # closes the loop by connecting last to first

    print(f"Wrote polyline with {N} vertices to {filename}")

    



def parse_sharp_edges_from_obj(path):
    """
    Parses OBJ comments of the form:
    # Sharp Edges: (12,10)&(4,9)

    Returns:
        List of tuples: [(11, 9), (3, 8)]
    (it converts from 1-based to 0-based to fir with trimesh)
    """
    sharp_edges = []

    pattern = re.compile(
        r"#\s*Sharp\s+Edges\s*:\s*(.*)"
    )

    with open(path, "r") as f:
        for line in f:
            line = line.strip()

            match = pattern.match(line)
            if not match:
                continue

            payload = match.group(1)

            # Find all (a,b) pairs
            pairs = re.findall(r"\(\s*(\d+)\s*,\s*(\d+)\s*\)", payload)

            for a, b in pairs:
                sharp_edges.append((int(a)-1, int(b)-1))

    return sharp_edges



    
def normalise_to_unit_bbox(o3d_mesh):

    vertices = np.asarray(o3d_mesh.vertices)
    
    min_vals = np.min(vertices, axis=0)
    max_vals = np.max(vertices, axis=0)
    
    # Shift the vertices by subtracting the minimum values for each axis
    vertices = vertices - min_vals

    ranges = max_vals - min_vals
    scale = 1.0 / np.max(ranges)
    print(scale)
    
    # Scale the shifted vertices so that the largest extent in any axis is 0.5
    vertices = vertices * scale
    
    vertices = vertices - 0.5

    new_min_vals = np.min(vertices, axis=0)
    new_max_vals = np.max(vertices, axis=0)

    vertices = vertices - (new_min_vals+new_max_vals)/2

    # Update the mesh
    o3d_mesh.vertices = o3d.utility.Vector3dVector(vertices)
    o3d_mesh.compute_vertex_normals()
    
    return o3d_mesh






def convert_off_file(input_file, output_file):
    ''' Converts a .off file to a .txt file in the
    format required by the geodesic_matlab repo.'''
    
    with open(input_file, 'r') as infile:
        lines = infile.readlines()
    
    if lines[0].strip() == "OFF":
        lines = lines[1:]
    
    header = list(map(int, lines[0].strip().split()))
    if len(header) == 3:
        num_vertices, num_faces, _ = header  # Ignore the number of edges
    else:
        raise ValueError("Invalid OFF file header")
    
    vertices = lines[1:num_vertices + 1]
    faces = lines[num_vertices + 1:num_vertices + 1 + num_faces]
    
    cleaned_faces = []
    for face in faces:
        indices = list(map(int, face.strip().split()))
        cleaned_faces.append(" ".join(map(str, indices[1:])))  # Strip number of vertices per face
    
    with open(output_file, 'w') as outfile:
        outfile.write(f"{num_vertices} {num_faces}\n")
        outfile.writelines(vertices)
        outfile.writelines(cleaned_face + "\n" for cleaned_face in cleaned_faces)
    
    print(f"Processed file saved as {output_file}")


def edge_split(he_mesh, V_he, edge_id, vtx_position=None, test_noise=False):
    """
    Splits an edge in a half-edge mesh into two edges by inserting a new vertex.

    :param he_mesh: The half-edge mesh (o3d.geometry.HalfEdgeTriangleMesh)
    :param edge_id: The index of the edge to be split
    :param new_vtx_id: The index of the new vertex
    :return: Updated half-edge mesh

                               ● v4
                              /|\ 
                             / | \ 
                            /  |  \
                           /   |   \
                          /    |    \
                         /     |     \              
                        /      |      \
                       /       |       \
                      /        |        \
                     /       ^ |         \
                    / /      | | |     |\ \
                   / a      h2 | h3      d \
                  / /        | | |        \ \
                 / L           | v           \
                /              |              \
               /       t2      |        t3     \
              /                |                \
             /      --h1-->    |     --h4-->     \
         v2 ●------------------●------------------● v1
             \      <--h0--    |    <--h5--      /
              \                |                /
               \               |               /
                \      t1      |      t4      /
                 \             |             /
                  \ \        ^ | |          /
                   \ b       | | h6        /
                    \ \|     h7| |        /
                     \       | | v    _  /
                      \        |      / /
                       \       |     c /
                        \      |    / /
                         \     |     /
                          \    |    /
                           \   |   /
                            \  |  /
                             \ | /
                              \|/
                               ● v3
    """
    
    #print(he_mesh.half_edges)

    
    #print(len(he_mesh.triangles))

    #old_he_mesh = copy.deepcopy(he_mesh)

    V = np.asarray(he_mesh.vertices)

    next_vtx_id = len(he_mesh.vertices)
    next_triangle_id = len(he_mesh.triangles)

    # Get original half-edges
    he = he_mesh.half_edges[edge_id]
    if he.twin is None:
        raise ValueError(f"Half-edge {edge_id} has no twin, cannot split.")
    he_twin = he_mesh.half_edges[he.twin]

    ################### vertices ##############
    v1 = he.vertex_indices[0]
    v2 = he.vertex_indices[1]
    v3 = he_mesh.half_edges[ he.next].vertex_indices[1]
    v4 = he_mesh.half_edges[ he_twin.next].vertex_indices[1]

    if vtx_position is None:
        vtx_position = (V[v1,:]+V[v2,:])/2
    if test_noise == True:
        vtx_position += 0.1*np.random.randn(3)

    v5 = len(he_mesh.vertices)
        
    he_mesh.vertices.append(vtx_position) #add midpoint vertex
    
    #################################################


    ###################
                           
    # Assign new triangles
    #print('halfedge:',he)
    
    he_mesh.triangles[he.triangle_index] = [next_vtx_id, v2, v3] #update old triangle
    he_mesh.triangles[he_twin.triangle_index] = [next_vtx_id, v4, v2] # update old triangle
    
    
    he_mesh.triangles.append ( [next_vtx_id, v1, v4] ) # new triangle
    he_mesh.triangles.append ( [next_vtx_id, v3, v1] ) # new triangle

    t1 = he.triangle_index
    t2 = he_twin.triangle_index
    t3 = next_triangle_id
    t4 = next_triangle_id + 1

    #print('triangle ind', t1,t2,t3,t4)

    #############
    

    # Create new half-edges (8 in total)
    new_hes = [o3d.geometry.HalfEdge() for _ in range(8)]

    # Assign new vertex indices
    #print('nxt vtx id', next_vtx_id, v2)
    new_hes[0].vertex_indices = [next_vtx_id, v2]
    new_hes[1].vertex_indices = [v2, next_vtx_id]
    new_hes[2].vertex_indices = [next_vtx_id, v4]
    new_hes[3].vertex_indices = [v4, next_vtx_id]
    
    new_hes[4].vertex_indices = [next_vtx_id, v1]
    new_hes[5].vertex_indices = [v1, next_vtx_id]
    new_hes[6].vertex_indices = [next_vtx_id, v3]
    new_hes[7].vertex_indices = [v3, next_vtx_id]

    next_he_id = len(he_mesh.half_edges)
    
    h0  = edge_id
    h1 = he.twin
    h2,h3,h4,h5,h6,h7 = [next_he_id + i for i in range(6) ]

    a = he_mesh.half_edges[ he_twin.next ].next
    b = he.next
    c = he_mesh.half_edges[ he.next ].next
    d = he_twin.next

    
    # Update twin relationships
    new_hes[0].twin = h1
    new_hes[1].twin = h0

    new_hes[2].twin = h3
    new_hes[3].twin = h2

    new_hes[4].twin = h5
    new_hes[5].twin = h4

    new_hes[6].twin = h7
    new_hes[7].twin = h6

    # Update next half-edge pointers
    new_hes[0].next = b
    new_hes[1].next = h2
    new_hes[2].next = a
    new_hes[3].next = h4

    new_hes[4].next = d
    new_hes[5].next = h6
    new_hes[6].next = c
    new_hes[7].next = h0

    # triangle indices
    new_hes[0].triangle_index = t1
    new_hes[1].triangle_index = t2
    new_hes[2].triangle_index = t2
    new_hes[3].triangle_index = t3
    new_hes[4].triangle_index = t3
    new_hes[5].triangle_index = t4
    new_hes[6].triangle_index = t4
    new_hes[7].triangle_index = t1
    


    # Replace old half-edges in the mesh
    
    he_mesh.half_edges[edge_id].vertex_indices = new_hes[0].vertex_indices
    he_mesh.half_edges[edge_id].twin = new_hes[0].twin
    he_mesh.half_edges[edge_id].next = new_hes[0].next
    he_mesh.half_edges[edge_id].triangle_index = new_hes[0].triangle_index
    
    he_mesh.half_edges[he.twin].vertex_indices = new_hes[1].vertex_indices
    he_mesh.half_edges[he.twin].twin = new_hes[1].twin
    he_mesh.half_edges[he.twin].next = new_hes[1].next
    he_mesh.half_edges[he.twin].triangle_index = new_hes[1].triangle_index


    

    he_mesh.half_edges[a].next = h1
    he_mesh.half_edges[a].triangle_index = t2

    he_mesh.half_edges[b].next = h7
    he_mesh.half_edges[b].triangle_index = t1

    he_mesh.half_edges[c].next = h5
    he_mesh.half_edges[c].triangle_index = t4

    he_mesh.half_edges[d].next = h3
    he_mesh.half_edges[d].triangle_index = t3
    
    # Append new half-edges
    temp = he_mesh.half_edges
    temp.extend(new_hes[2:])
    he_mesh.half_edges = temp


    # update V_he
    V_he.append(h0)
    V_he[v1] = h5
    V_he[v2] = h1
    V_he[v3] = h7
    V_he[v4] = h3

    involved_halfedges = (h0,h1,h2,h3,h4,h5,h6,h7)

    return he_mesh, V_he, involved_halfedges




def dist(p, a, b):
    ab = b - a
    ap = p - a
    proj_length = np.dot(ap, ab) / np.dot(ab, ab)  # Projection scalar
    proj_point = a + proj_length * ab  # Projection point on line
    return np.linalg.norm(p - proj_point), proj_length  # Euclidean distance

    
def point_on_segment(p, a, b, tol=1e-4):
    d, s = dist(p, a, b)
    #print(d)
    if d<tol and 0-tol<=s and s<=1+tol:
        return True
    return False


'''
def point_on_segment(p, a, b, tol=1e-8):
    ab = b - a
    ap = p - a

    # Check if colinear 
    cross = np.cross(ab, ap)
    print((cross**2).sum())
    if (cross**2).sum() > tol:
        return False

    # Check if p is between a and b using dot product
    dot = np.dot(ap, ab)
    if dot < 0 or dot > np.dot(ab, ab):
        return False

    return True
'''

    
def ordered_onering_halfedges(he_mesh, V_he, vtx_id):
    first_he = V_he[vtx_id]
    cur_he = first_he
    
    ring_halfedges = []
    new_he=True
    while new_he:
        
        ring_halfedges.append(he_mesh.half_edges[ cur_he ].next)
        cur_he = he_mesh.half_edges[ he_mesh.half_edges[ cur_he ].twin ].next
        if cur_he == first_he:
            new_he=False
            
    return ring_halfedges[::-1]



def onering_halfedges_with_radials(he_mesh, V_he, vtx_id):
    first_he = V_he[vtx_id]
    cur_he = first_he
    
    ring_halfedges = []
    new_he=True
    while new_he:

        ring_halfedges.append(cur_he) # also include radials
        
        ring_halfedges.append(he_mesh.half_edges[ cur_he ].next)
        cur_he = he_mesh.half_edges[ he_mesh.half_edges[ cur_he ].twin ].next

        if cur_he == first_he:
            new_he=False
            
    return ring_halfedges[::-1]



def ordered_radial_halfedges(he_mesh, V_he, vtx_id):
    first_he = V_he[vtx_id]
    cur_he = first_he
    
    ring_halfedges = []
    new_he=True
    while new_he:

        ring_halfedges.append(cur_he) # also include radials
        
        #ring_halfedges.append(he_mesh.half_edges[ cur_he ].next)
        cur_he = he_mesh.half_edges[ he_mesh.half_edges[ cur_he ].twin ].next

        if cur_he == first_he:
            new_he=False
            
    return ring_halfedges[::-1]


    

def he_mesh_from_file(mesh_filepath):
    mesh_o3d = o3d.io.read_triangle_mesh(mesh_filepath)
    mesh_o3d.compute_vertex_normals()
    he_mesh = o3d.geometry.HalfEdgeTriangleMesh.create_from_triangle_mesh(mesh_o3d)

    V_he = get_V_he(he_mesh)
    
    return he_mesh, V_he


def he_mesh_from_o3d(mesh_o3d):
    
    he_mesh = o3d.geometry.HalfEdgeTriangleMesh.create_from_triangle_mesh(mesh_o3d)
    V_he = get_V_he(he_mesh)
    
    return he_mesh, V_he

def o3d_mesh_from_file(mesh_filepath):
    
    mesh_o3d = o3d.io.read_triangle_mesh(mesh_filepath)
    return mesh_o3d


def o3d_mesh_from_he_mesh(he_mesh):
    mesh = o3d.geometry.TriangleMesh()
    mesh.vertices = o3d.utility.Vector3dVector(np.asarray(he_mesh.vertices))
    mesh.triangles = o3d.utility.Vector3iVector(np.asarray(he_mesh.triangles))
    return mesh
    

def get_V_he(he_mesh):

    print('Preparing V_he for halfedge mesh')

    V_he = [-1] * len(he_mesh.vertices)  # More efficient than list comprehension

    for i, he in enumerate(he_mesh.half_edges):
        if i % 10000 == 0 and i!=0:
            print(i, 'of', len(he_mesh.half_edges))
    
        V_he[he.vertex_indices[0]] = i  # Direct attribute access

    print('Prepared V_he for halfedge mesh.')
    print()

    return V_he



def optimise_V_he(he_mesh, V_he):
    """
    Assigns each vertex a boundary halfedge if the vertex is on a boundary.
    For interior vertices, keeps the original V_he.
    """

    he = he_mesh.half_edges
    print('Optimising V_he.')

    for i, he_id_0 in enumerate(V_he):
        he_id = he_id_0
        start_he = he_id_0
        found_boundary = False

        while True:
            if he[he_id].twin == -1:
                # this halfedge is a boundary, assign it to V_he
                V_he[i] = he_id
                found_boundary = True
                break

            # move to next halfedge around the vertex
            he_id = he[he[he_id].twin].next

            if he_id == start_he:
                # looped around, no boundary halfedge found
                break

        # Optional: if not found_boundary, V_he[i] remains unchanged

    print('Finished optimising V_he.\n')
    return V_he


    





































'''
def optimise_V_he(he_mesh, V_he): #make a more meaningful vertex halfedge assignement: assign boundary halfedges where possible.

    he = he_mesh.half_edges

    print('Optimising V_he.')

    for i, he_id_0 in enumerate(V_he):
        
        he_id = he_id_0
        bdry = False
        
        while True:
            # traversing the onering backwards until we wrap around or reach a bdry
            twin_of_prev = he[he[he[he_id].next].next].twin

            if twin_of_prev == -1:
                V_he[i] = he_id
                break # this is what we want, when vtx is on a bdry
                
            if twin_of_prev == he_id_0:
                break # not a bdry, so V_he not important

            he_id = twin_of_prev #update he_id
  

    print('Finished optimising V_he.')
    print()

    return V_he
'''  
    


def do_mesh_cutting(he_mesh, V_he, geodesic_points, bdry_halfedge_mask, geodesic_pcd, first_vtx_id, left_face_id=1, right_face_id=1, debug_plot=False, verbose=False):
    n = len(geodesic_points)


    edge_id = None
    ended = False
    vtx_id = first_vtx_id
    vertex_indices = [vtx_id]

    geodesic_points.pop(0)
    
    while len(geodesic_points) > 0 and ended==False:


        if verbose:
            print(i, 'out of', n-1)


        q = geodesic_points.pop(0)
                
        #onering_halfedges = onering_halfedges_with_radials(he_mesh, V_he, vtx_id)
        onering_halfedges = ordered_onering_halfedges(he_mesh, V_he, vtx_id)
        

        count=0
        for j in onering_halfedges:
            
            a = he_mesh.vertices[he_mesh.half_edges[j].vertex_indices[0]]
            b = he_mesh.vertices[he_mesh.half_edges[j].vertex_indices[1]]
            
            if debug_plot:
                plt.plot([a[0], b[0]], [a[1], b[1]], color='black')
                plt.text(a[0], a[1], str(he_mesh.half_edges[j].vertex_indices[1]), fontsize=9, ha='left', va='bottom', color='black')

                
                plt.scatter([q[0]], [q[1]], color = 'orange')
                plt.text(q[0], q[1], 'q', fontsize=9, ha='left', va='bottom', color='orange')

                # Scatter the vertex point
                vx = he_mesh.vertices[vtx_id]
                plt.scatter(he_mesh.vertices[vtx_id][0], he_mesh.vertices[vtx_id][1], color='blue', alpha=0.5)
                #plt.text(vx[0], vx[1], f'vtx {vtx_id}', fontsize=9, ha='left', va='bottom', color='blue')

            if point_on_segment(q,a,b):
                if verbose:
                    print('point on segment',j)
                count+=1
                edge_id=j

        if count>=2:
            print('End of cutting section.')
            ended=True
            
            id_a = he_mesh.half_edges[edge_id].vertex_indices[0]
            id_b = he_mesh.half_edges[edge_id].vertex_indices[1]
            a = he_mesh.vertices[id_a]
            b = he_mesh.vertices[id_b]


            
            
            if ((q-a)**2).sum() < ((q-b)**2).sum():
                vtx_id = id_a

                new_bdry_halfedge_ids = [ he_mesh.half_edges[he_mesh.half_edges[edge_id].next].next,
                                         he_mesh.half_edges[ he_mesh.half_edges[he_mesh.half_edges[edge_id].next].next].twin ]
            else:
                vtx_id = id_b
                new_bdry_halfedge_ids = [ he_mesh.half_edges[edge_id].next,
                                         he_mesh.half_edges[he_mesh.half_edges[edge_id].next].twin ]

            bdry_halfedge_mask[new_bdry_halfedge_ids[0]] = left_face_id
            bdry_halfedge_mask[new_bdry_halfedge_ids[1]] = right_face_id

            

            
            
        elif count==0:


            

            
            print('Point not on any segment.')
            o3d.visualization.draw_geometries([he_mesh, geodesic_pcd], window_name="Error: stopped early")
            raise TypeError("Oh no... the geodesic vertices should all lie on edges of the mesh.")
            
        else:
            he_mesh, V_he, involved_halfedges = edge_split(he_mesh, V_he, edge_id=edge_id, vtx_position=q)
            vtx_id = len(he_mesh.vertices) - 1

            # apply halfedge updates to the bdry_halfedge_mask

            bdry_halfedge_mask = np.concatenate([bdry_halfedge_mask, -1* np.ones(6, dtype=int)]) #extend mask by 6
            # this is specific to how the edge was split - see diagram.
            h0, h1, h2, h3, h4, h5, h6, h7 = involved_halfedges
            if bdry_halfedge_mask[h0] >= 0:
                value = bdry_halfedge_mask[h1]
                bdry_halfedge_mask[h0] = -1 #clear previous
                bdry_halfedge_mask[halfedge_updates[h0][0]] = value
                bdry_halfedge_mask[halfedge_updates[h0][1]] = value

            if bdry_halfedge_mask[h1] >= 0:
                value = bdry_halfedge_mask[h1]
                
                bdry_halfedge_mask[h1] = -1 # clear previous
                bdry_halfedge_mask[halfedge_updates[h1][0]] = value
                bdry_halfedge_mask[halfedge_updates[h1][1]] = value

            #bdry_halfedge_mask[h6] = right_face_id
            #bdry_halfedge_mask[h7] = left_face_id
                

            #############################################

        vertex_indices.append(vtx_id) # keep track of the vertex indices passed through.
            
    if debug_plot:        
        plt.show()

    geodesic_points = [q] + geodesic_points

    #o3d.visualization.draw_geometries([he_mesh, geodesic_pcd], window_name="Cut along a part of a curve successfully.")


    return vertex_indices, geodesic_points, bdry_halfedge_mask
















        


def cut_mesh_along_geodesic_v2(he_mesh, V_he, geodesic_filepath, bdry_halfedge_mask, first_vtx_id, last_vtx_id, left_face_id=1, right_face_id=1, debug_plot=False, verbose=False):

    geodesic = trimesh.load(geodesic_filepath)
    geodesic_points = geodesic.vertices

    
    # Convert vertices to Open3D point cloud
    geodesic_pcd = o3d.geometry.PointCloud()
    geodesic_pcd.points = o3d.utility.Vector3dVector(geodesic_points)



    
    
    vertices = he_mesh.vertices  # or however you access the vertex array
    
    # Build KDTree
    tree = cKDTree(vertices)
    
    # Query nearest vertex for each point
    distances, indices = tree.query(geodesic_points)

    #plt.plot(distances)
    #plt.show()

    first_vtx_id = indices[0]

    #print(geodesic_points)
    remaining_geodesic_points = list(geodesic_points)

    print('Starting the cutting for a curve. First and last vertex id are', first_vtx_id, last_vtx_id )

    while len(remaining_geodesic_points) > 0:
        if verbose:
            print('Making a cut...')

        vertex_indices, remaining_geodesic_points, bdry_halfedge_mask = do_mesh_cutting(he_mesh, V_he, remaining_geodesic_points, bdry_halfedge_mask, geodesic_pcd, first_vtx_id, left_face_id=left_face_id, right_face_id=right_face_id, debug_plot=debug_plot, verbose=verbose)

        first_vtx_id = vertex_indices[-1]
        if verbose:
            print('now first vtx id is', first_vtx_id)
            print(len(remaining_geodesic_points), 'remaining')

    print('Cut along a curve successfully')

    return he_mesh, V_he, geodesic_pcd, vertex_indices, bdry_halfedge_mask







def do_mesh_cutting_v3(he_mesh, V_he, geodesic_points, bdry_halfedge_mask, geodesic_pcd, first_vtx_id, left_face_id=1, right_face_id=1, debug_plot=False, verbose=False):



    edge_id = None
    ended = False
    vtx_id = first_vtx_id
    vertex_indices = [vtx_id]

    if verbose:
        print('GEODESIC POINTS at start of do_mesh_cutting', len(geodesic_points))
        print('VERTEX INDICES at start of do_mesh_cutting', vertex_indices)
    
    ## to put in loop eventually
    q = geodesic_points.pop(-1)

            
    #onering_halfedges = onering_halfedges_with_radials(he_mesh, V_he, vtx_id)
    onering_halfedges = ordered_onering_halfedges(he_mesh, V_he, vtx_id)
    

    count=0
    for j in onering_halfedges:
        
        a = he_mesh.vertices[he_mesh.half_edges[j].vertex_indices[0]]
        b = he_mesh.vertices[he_mesh.half_edges[j].vertex_indices[1]]

        if debug_plot:

            plt.plot([a[0], b[0]], [a[1], b[1]], color='black')
            plt.text(a[0], a[1], str(he_mesh.half_edges[j].vertex_indices[1]), fontsize=9, ha='left', va='bottom', color='black')
    
                    
            plt.scatter([q[0]], [q[1]], color = 'orange')
            plt.text(q[0], q[1], 'q', fontsize=9, ha='left', va='bottom', color='orange')
    
             # Scatter the vertex point
            vx = he_mesh.vertices[vtx_id]
            plt.scatter(vx[0], vx[1], color='blue', alpha=0.5)
            plt.text(vx[0], vx[1], 'vx'+str(vtx_id), fontsize=9, ha='left', va='bottom', color='blue')
        

        if point_on_segment(q,a,b):
            if verbose:
                print('point on segment',j)
            count+=1
            edge_id=j

    if debug_plot:
        plt.show()

    if verbose:
        print('COUNT is', count)

    if count>=2:
        if verbose:
            print('End of cutting section, because it reached an original vertex.')
        ended=True
        
        id_a = he_mesh.half_edges[edge_id].vertex_indices[0]
        id_b = he_mesh.half_edges[edge_id].vertex_indices[1]
        a = he_mesh.vertices[id_a]
        b = he_mesh.vertices[id_b]


        
        
        if ((q-a)**2).sum() < ((q-b)**2).sum():
            vtx_id = id_a

            new_bdry_halfedge_ids = [ he_mesh.half_edges[he_mesh.half_edges[edge_id].next].next,
                                     he_mesh.half_edges[ he_mesh.half_edges[he_mesh.half_edges[edge_id].next].next].twin ]
        else:
            vtx_id = id_b
            new_bdry_halfedge_ids = [ he_mesh.half_edges[edge_id].next,
                                     he_mesh.half_edges[he_mesh.half_edges[edge_id].next].twin ]

        bdry_halfedge_mask[new_bdry_halfedge_ids[0]] = left_face_id
        bdry_halfedge_mask[new_bdry_halfedge_ids[1]] = right_face_id

    elif count==1:
        he_mesh, V_he, involved_halfedges = edge_split(he_mesh, V_he, edge_id=edge_id, vtx_position=q)
        vtx_id = len(he_mesh.vertices) - 1

        # apply halfedge updates to the bdry_halfedge_mask

        bdry_halfedge_mask = np.concatenate([bdry_halfedge_mask, -1* np.ones(6, dtype=int)]) #extend mask by 6
        # this is specific to how the edge was split - see diagram.
        h0, h1, h2, h3, h4, h5, h6, h7 = involved_halfedges
        
        '''
        if bdry_halfedge_mask[h0] >= 0:
            value = bdry_halfedge_mask[h1]
            bdry_halfedge_mask[h0] = -1 #clear previous
            bdry_halfedge_mask[halfedge_updates[h0][0]] = value
            bdry_halfedge_mask[halfedge_updates[h0][1]] = value

        if bdry_halfedge_mask[h1] >= 0:
            value = bdry_halfedge_mask[h1]
            
            bdry_halfedge_mask[h1] = -1 # clear previous
            bdry_halfedge_mask[halfedge_updates[h1][0]] = value
            bdry_halfedge_mask[halfedge_updates[h1][1]] = value

        '''

        bdry_halfedge_mask[h6] = right_face_id
        bdry_halfedge_mask[h7] = left_face_id

    

    elif count==0:

        radial_halfedges = ordered_radial_halfedges(he_mesh, V_he, vtx_id)

        found_radial=False
        
        for j in radial_halfedges:
            
            a = he_mesh.vertices[he_mesh.half_edges[j].vertex_indices[0]]
            b = he_mesh.vertices[he_mesh.half_edges[j].vertex_indices[1]]

            if debug_plot==True:
    
            
    
                plt.plot([a[0], b[0]], [a[1], b[1]], color='red')
                plt.text(a[0], a[1], str(he_mesh.half_edges[j].vertex_indices[1]), fontsize=9, ha='left', va='bottom', color='black')
            
                            
                plt.scatter([q[0]], [q[1]], color = 'orange')
                plt.text(q[0], q[1], 'q', fontsize=9, ha='left', va='bottom', color='orange')
            
                # Scatter the vertex point
                vx = he_mesh.vertices[vtx_id]
                plt.scatter(vx[0], vx[1], color='blue', alpha=0.5)
                plt.text(vx[0], vx[1], 'vx'+str(vtx_id), fontsize=9, ha='left', va='bottom', color='blue')
            
    
            if point_on_segment(q,a,b):
                if verbose:
                    print('point on segment',j)
                edge_id=j
                found_radial=True
                
        if debug_plot==True:
            plt.show()


        
        
        if found_radial==False:
            print('Point not on any segment.')
            o3d.visualization.draw_geometries([he_mesh, geodesic_pcd], window_name="Error: stopped early")
            raise TypeError("Oh no... the geodesic vertices should all lie on edges of the mesh.")


        #split edge on radial
        
        he_mesh, V_he, involved_halfedges = edge_split(he_mesh, V_he, edge_id=edge_id, vtx_position=q)
        vtx_id = len(he_mesh.vertices) - 1

        # apply halfedge updates to the bdry_halfedge_mask

        bdry_halfedge_mask = np.concatenate([bdry_halfedge_mask, -1* np.ones(6, dtype=int)]) #extend mask by 6
        # this is specific to how the edge was split - see diagram.
        h0, h1, h2, h3, h4, h5, h6, h7 = involved_halfedges

        '''
        if bdry_halfedge_mask[h0] >= 0:
            value = bdry_halfedge_mask[h1]
            bdry_halfedge_mask[h0] = -1 #clear previous
            bdry_halfedge_mask[halfedge_updates[h0][0]] = value
            bdry_halfedge_mask[halfedge_updates[h0][1]] = value

        if bdry_halfedge_mask[h1] >= 0:
            value = bdry_halfedge_mask[h1]
            
            bdry_halfedge_mask[h1] = -1 # clear previous
            bdry_halfedge_mask[halfedge_updates[h1][0]] = value
            bdry_halfedge_mask[halfedge_updates[h1][1]] = value
        '''

        bdry_halfedge_mask[h5] = right_face_id
        bdry_halfedge_mask[h4] = left_face_id

        
            
    

    vertex_indices.append(vtx_id)
    if verbose:
        print('GEODESIC POINTS at end of do_mesh_cutting', len(geodesic_points))
        print('VERTEX INDICES at end of do_mesh_cutting', vertex_indices)
            
    


    return vertex_indices, geodesic_points, bdry_halfedge_mask





def cut_mesh_along_geodesic_v3(he_mesh, V_he, geodesic_filepath, bdry_halfedge_mask, first_vtx_id, last_vtx_id, left_face_id=1, right_face_id=1, debug_plot=False, verbose=False):

    geodesic = trimesh.load(geodesic_filepath)
    geodesic_points = geodesic.vertices

    
    # Convert vertices to Open3D point cloud
    geodesic_pcd = o3d.geometry.PointCloud()
    geodesic_pcd.points = o3d.utility.Vector3dVector(geodesic_points)


    remaining_geodesic_points = list(geodesic_points)[1:][::-1]

    print('Starting the cutting for a curve. First and last vertex id are', first_vtx_id, last_vtx_id )

    while len(remaining_geodesic_points) > 0:
        if verbose:
            print('Making a cut...')

        vertex_indices, remaining_geodesic_points, bdry_halfedge_mask = do_mesh_cutting_v3 (he_mesh, V_he, remaining_geodesic_points, bdry_halfedge_mask, geodesic_pcd, first_vtx_id, left_face_id=left_face_id, right_face_id=right_face_id, debug_plot=debug_plot, verbose=verbose)

        first_vtx_id = vertex_indices[-1]
        if verbose:
            print('now first vtx id is', first_vtx_id)
            print(len(remaining_geodesic_points), 'remaining')

    
    print('Cut along a curve successfully')

    return he_mesh, V_he, geodesic_pcd, vertex_indices, bdry_halfedge_mask















def floodfill(seed_he_index, fine_half_edges, bdry_halfedge_mask, V_fine ):
    ''' floodfill a region of a halfedge mesh, given a seed halfedge.
    returns triangle indices of flooded faces. 
    fine_half_edges are o3d halfedge pointers, and all_bdry_halfedges
    is a list of vertex-pair tuples.'''

    if bdry_halfedge_mask.dtype==int:
        bdry_halfedge_mask = (bdry_halfedge_mask>=0)

    visited = set()
    queue = deque([seed_he_index])
    triangle_indices = set()

    while queue:
        he_index = queue.popleft()
        if he_index in visited:
            continue
        visited.add(he_index)
    
        v_ids = fine_half_edges[he_index].vertex_indices
    
        v0 = V_fine[ v_ids[0] ]
        v1 = V_fine[ v_ids[1] ]
    
        #plt.plot([ v0[0], v1[0]], [v0[1], v1[1]], alpha=0.2, color='red')
        triangle_indices.add(fine_half_edges[he_index].triangle_index)
        
        if fine_half_edges[he_index].next not in visited:
                queue.append(fine_half_edges[he_index].next)

        #if ((v_ids[0], v_ids[1]) in all_bdry_halfedges):
        #    #plt.plot([ v0[0], v1[0]], [v0[1], v1[1]], alpha=0.2, color='blue')
        #    continue

        if bdry_halfedge_mask[he_index] :
            #plt.plot([ v0[0], v1[0]], [v0[1], v1[1]], alpha=0.2, color='blue')
            continue
            
        else:
            if fine_half_edges[he_index].twin not in visited:
                queue.append(fine_half_edges[he_index].twin)

    #plt.axis('equal')
    #plt.show()

    return triangle_indices




def read_special_indices_from_obj(obj_file_path):
    # Open the file and read the first line
    with open(obj_file_path, "r") as file:
        first_line = file.readline().strip()

    # Extract the indices from the comment line if it starts with "# Special vertex indices"
    if first_line.startswith("# Coarse Triangle Correspondence"):
        # Remove the prefix and convert the string of indices into a list of integers
        return list(map(int, first_line[len("# Coarse Triangle Correspondence: "):].split(", ")))

    print(f"No special vertex indices found in {obj_file_path}")
    return None



    

def tutte_embedding(input_filename, output_filename, visualise=False):
    
    mesh = o3d.io.read_triangle_mesh(input_filename)

    
    V = np.asarray(mesh.vertices)  # Vertices as a numpy array
    F = np.asarray(mesh.triangles)  # Faces as a numpy array
    
    # Get boundary loop
    boundary = list ( igl.boundary_loop(F) )

    coarse_triangle_vtx_indices = read_special_indices_from_obj(input_filename)
    
    print('boundary:', boundary)
    print(coarse_triangle_vtx_indices)
    
    
    ###########################################################################
    '''
    # Map boundary vertices to the unit circle (convex polygon)
    num_boundary = len(boundary)
    angles = np.linspace(0, 2 * np.pi, num_boundary, endpoint=False)
    boundary_uv = np.column_stack((np.cos(angles), np.sin(angles)))
    '''
    
    # Triangle corners: unit side length, one at origin
    triangle_corners = np.array([
        [0.0, 0.0],
        [1.0, 0.0],
        [0.5, np.sqrt(3)/2]
    ])

    # Find boundary indices of the 3 special vertices in the given order (no sorting)
    corner_idx = [boundary.index(idx) for idx in coarse_triangle_vtx_indices]
    
    # Wrap the boundary and extract the 3 segments in cyclic order
    segments = []
    for i in range(3):
        start = corner_idx[i]
        end = corner_idx[(i + 1) % 3]
        if start < end:
            segment = boundary[start:end + 1]
        else:
            segment = boundary[start:] + boundary[:end + 1]
        segments.append(segment)
    
    # Total boundary length
    bdry_points = np.array([V[idx] for idx in boundary])
    lengths = np.linalg.norm(np.roll(bdry_points, -1, axis=0) - bdry_points, axis=1)
    total_length = np.sum(lengths)
    
    # Map each segment to a triangle edge proportionally
    boundary_uv = np.zeros((len(boundary), 2))
    
    for seg, (start_pt, end_pt) in zip(segments, zip(triangle_corners, np.roll(triangle_corners, -1, axis=0))):
        # Compute cumulative arclength along this segment
        seg_points = np.array([V[i] for i in seg])
        seg_lengths = np.linalg.norm(np.diff(seg_points, axis=0), axis=1)
        seg_lengths = np.insert(np.cumsum(seg_lengths), 0, 0.0)
        seg_total = seg_lengths[-1]
    
        # Linearly interpolate UVs along this edge
        for i, s in enumerate(seg):
            t = seg_lengths[i] / seg_total if seg_total > 0 else 0
            uv = (1 - t) * start_pt + t * end_pt
            boundary_uv[boundary.index(s)] = uv
    
            
    
    
    ###########################################################################
    
    
    
    # Indices of boundary vertices and their target UVs
    b = np.array(boundary, dtype=np.int32)
    bc = boundary_uv.astype(np.float64)
    
    # Harmonic mapping (Tutte-style, k=1)
    UV = igl.harmonic(V, F, b, bc, 1)
    
    
    with open(output_filename, 'w') as f:
        # Write vertices
        for vertex in V:
            f.write(f"v {vertex[0]} {vertex[1]} {vertex[2]}\n")
        
        # Write texture coordinates (UVs)
        for uv_coord in UV:
            f.write(f"vt {uv_coord[0]} {uv_coord[1]}\n")
    
        # Write faces (adjust to include texture coordinates)
        for face in F:
            # OBJ format requires faces to include texture coordinates: 
            # "f v1/vt1 v2/vt2 v3/vt3"
            f.write(f"f {face[0]+1}/{face[0]+1} {face[1]+1}/{face[1]+1} {face[2]+1}/{face[2]+1}\n")
    
    print(f"Tutte-style harmonic embedding completed. UVs saved to {output_filename}")

    if visualise==True:
        # show a 3d plot of the mesh and a 2d plot of the flattened mesh

        # Create the figure and subplots
        fig = plt.figure(figsize=(12, 6))
        
        # ---------- 3D Mesh Plot ----------
        ax3d = fig.add_subplot(121, projection='3d')
        for face in F:
            verts = V[face]
            poly3d = Poly3DCollection([verts], color='blue', linewidths=1, edgecolors='blue', alpha=0.2)
            ax3d.add_collection3d(poly3d)
        
        # Label vertices in 3D
        for i, v in enumerate(V):
            ax3d.text(v[0], v[1], v[2], f'{i}', color='black', fontsize=10, ha='right')
        
        ax3d.set_title("3D Mesh")
        ax3d.set_xlabel('X')
        ax3d.set_ylabel('Y')
        ax3d.set_zlabel('Z')
        ax3d.set_xlim([V[:, 0].min(), V[:, 0].max()])
        ax3d.set_ylim([V[:, 1].min(), V[:, 1].max()])
        ax3d.set_zlim([V[:, 2].min(), V[:, 2].max()])
        
        # ---------- 2D UV Plot ----------
        ax2d = fig.add_subplot(122)
        for face in F:
            uv_coords = UV[face]
            polygon = plt.Polygon(uv_coords, edgecolor='blue', facecolor='cyan', alpha=0.3)
            ax2d.add_patch(polygon)
        
        # Label UV vertices
        for i, uv in enumerate(UV):
            ax2d.text(uv[0], uv[1], f'{i}', color='black', fontsize=10, ha='center')
        
        ax2d.set_title("UV Layout")
        ax2d.set_xlabel('U')
        ax2d.set_ylabel('V')
        ax2d.set_aspect('equal')
        ax2d.set_xlim([UV[:, 0].min(), UV[:, 0].max()])
        ax2d.set_ylim([UV[:, 1].min(), UV[:, 1].max()])
        
        plt.tight_layout()
        plt.show()
        
        # Optional prints
        print('boundary:', boundary)
        print('coarse_triangle_vtx_indices:', coarse_triangle_vtx_indices)


def vertex_uvs_from_face_uvs(faces, face_uvs):
    
    
    vertex_count = faces.max() + 1
    vertex_uvs = np.zeros((vertex_count, 2))

    for face_idx, verts in enumerate(faces):
        for corner_idx, v_idx in enumerate(verts):
            uv = face_uvs[face_idx * 3 + corner_idx]
            vertex_uvs[v_idx] = uv

    return vertex_uvs
    





